"""Settlement engine service: API plus a periodic scheduler that settles each
closed period (end + grace) once."""

import asyncio
import datetime as dt
import json
import logging
from typing import Any

import uvicorn

from dots_common.client import DotsClient
from dots_common.identity import NodeIdentity
from dots_common.models import SignedRateTable

from .app import create_app
from .config import Settings
from .engine import Engine, Store
from .fraud import OvsConfig, RulesConfig, build_gate
from .payout import FiatStub, Payout, StablecoinConfig, StablecoinTestnet

log = logging.getLogger("dots.settlement")


def build(s: Settings) -> tuple[Engine, dict[str, Payout]]:
    client = DotsClient.from_state(s.identity, s.state)
    ident = NodeIdentity.load(s.identity, s.state / s.identity / "keys")
    tables = [
        SignedRateTable.model_validate(json.loads(p.read_text()))
        for p in sorted((s.state / "rates").glob("*.json"))
    ]
    gate = build_gate(
        RulesConfig(),
        OvsConfig(
            enabled=s.ovs_enabled,
            base_url=s.ovs_base_url,
            api_key=s.ovs_api_key,
            timeout_ms=s.ovs_timeout_ms,
            fail_mode=s.ovs_fail_mode,
        ),
    )
    engine = Engine(
        ident,
        client,
        gate,
        Store(s.data_dir / "settlement.sqlite3"),
        tables,
        grace_ms=s.grace_hours * 3_600_000,
    )
    payouts: dict[str, Payout] = {}
    for name in [n.strip() for n in s.payout_adapters.split(",") if n.strip()]:
        if name == "fiat_stub":
            payouts[name] = FiatStub(s.data_dir / "invoices")
        elif name == "stablecoin_testnet":
            payouts[name] = _stablecoin(s, client)
        else:
            raise ValueError(f"unknown payout adapter {name}")
    return engine, payouts


def _stablecoin(s: Settings, client: DotsClient) -> Payout:
    """Lab only: pays from the payer's testnet wallet generated by the bootstrap."""
    addresses: dict[str, str] = {
        p.node_id: p.settlement_address
        for p in client.keyring.registry.peers
        if p.settlement_address
    }

    class PerPayer:
        name = "stablecoin_testnet"

        def pay(self, ss: Any) -> dict[str, Any]:
            payer = ss.statement.net.payer
            key = (s.state / payer / "wallet.key").read_text().strip()
            return StablecoinTestnet(
                StablecoinConfig(
                    chain_id=s.stablecoin_chain_id,
                    rpc_url=s.stablecoin_rpc_url,
                    dry_run=s.stablecoin_dry_run,
                ),
                key,
                addresses,
            ).pay(ss)

    return PerPayer()


async def scheduler(engine: Engine, s: Settings) -> None:
    """Settle yesterday (UTC) once its grace period has passed."""
    done: set[str] = set()
    while True:
        now = dt.datetime.now(dt.UTC)
        period = (now - dt.timedelta(days=1)).strftime("%Y-%m-%d")
        closes = dt.datetime.strptime(period, "%Y-%m-%d").replace(tzinfo=dt.UTC) + dt.timedelta(
            days=1, hours=s.grace_hours
        )
        if period not in done and now >= closes:
            try:
                await asyncio.to_thread(engine.run, period)
                done.add(period)
            except Exception:
                log.exception("scheduled settlement for %s failed", period)
        await asyncio.sleep(s.schedule_interval_s)


async def serve(s: Settings) -> None:
    engine, payouts = build(s)
    server = uvicorn.Server(
        uvicorn.Config(
            create_app(engine, payouts, s.lab_mode),
            host=s.listen_host,
            port=s.listen_port,
            log_level="info",
            access_log=False,
        )
    )
    task = asyncio.create_task(scheduler(engine, s))
    try:
        await server.serve()
    finally:
        task.cancel()


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s %(message)s")
    asyncio.run(serve(Settings()))


if __name__ == "__main__":
    main()
