#!/bin/sh
# Render instance-level Kamailio config from the environment and start.
#   DOTS_NODE_ID       node id (operator identity), e.g. node-a
#   DOTS_ACCESS_NET    customer/PBX subnet, e.g. 172.30.10.0/24
#   DOTS_DMQ_PEERS     other instances of this operator (host names), may be empty
#   DOTS_RTPENGINE     rtpengine host name
#   DOTS_RECEIPTS_URL  internal URL of the local receipt service
set -eu
: "${DOTS_NODE_ID:?}" "${DOTS_ACCESS_NET:?}" "${DOTS_RTPENGINE:?}" "${DOTS_RECEIPTS_URL:?}"
STATE=/state/$DOTS_NODE_ID

for i in $(seq 1 60); do [ -f /state/bootstrap.done ] && break; sleep 1; done
[ -f /state/bootstrap.done ] || { echo "lab state missing" >&2; exit 1; }

resolve() { getent ahostsv4 "$1" | awk 'NR==1{print $1}'; }
MY_IP=$(hostname -i | awk '{print $1}')
RTP_IP=""
for i in $(seq 1 30); do RTP_IP=$(resolve "$DOTS_RTPENGINE") && [ -n "$RTP_IP" ] && break; sleep 1; done
NOTIFY="sip:$MY_IP:5061;transport=tls"
for peer in ${DOTS_DMQ_PEERS:-}; do
  for i in $(seq 1 30); do PIP=$(resolve "$peer") && [ -n "$PIP" ] && break; sleep 1; done
  NOTIFY="sip:$PIP:5061;transport=tls"
done

cat > /etc/kamailio/instance.cfg <<CFG
# Generated by entrypoint.sh at container start.
listen=udp:$MY_IP:5060
listen=tls:$MY_IP:5061
listen=tcp:$MY_IP:8088
alias="$DOTS_NODE_ID"
alias="$(hostname)"
#!substdef "!DOTS_ACCESS_NET!$DOTS_ACCESS_NET!g"
#!substdef "!DOTS_DMQ_SELF!sip:$MY_IP:5061;transport=tls!g"
#!substdef "!DOTS_DMQ_NOTIFY!$NOTIFY!g"
#!substdef "!DOTS_RTPENGINE_SOCK!udp:$RTP_IP:2223!g"
#!substdef "!DOTS_RECEIPTS_URL!$DOTS_RECEIPTS_URL!g"
#!substdef "!DOTS_INTERNAL_TOKEN!$(cat "$STATE/token")!g"
CFG
cp "$STATE/kamailio/node.cfg" /etc/kamailio/node.cfg

cat > /etc/kamailio/tls.cfg <<CFG
[server:default]
method = TLSv1.2+
verify_certificate = yes
require_certificate = yes
private_key = $STATE/tls/key.pem
certificate = $STATE/tls/cert.pem
ca_list = /state/ca/ca.pem

[client:default]
method = TLSv1.2+
verify_certificate = yes
require_certificate = yes
private_key = $STATE/tls/key.pem
certificate = $STATE/tls/cert.pem
ca_list = /state/ca/ca.pem
CFG

mkdir -p /tmp/secsipid
kamailio -c -f /etc/kamailio/kamailio.cfg
exec kamailio -DD -E -f /etc/kamailio/kamailio.cfg
